x-airflow-common: &airflow-common
  image: custom-airflow:latest   # à¹ƒà¸Šà¹‰ image à¹€à¸”à¸µà¸¢à¸§
  environment:
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/src/dags
    PYTHONPATH: /opt/airflow/src
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'

  volumes:
    - ./:/opt/airflow            
    # - ./src/dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./src/spark:/opt/airflow/spark          # mount spark jobs
    # - ./src/script:/opt/airflow/script        # mount entrypoint.sh à¸«à¸£à¸·à¸­ script à¸­à¸·à¹ˆà¸™
    # - ./instance:/opt/airflow/instance        # mount database.db à¸–à¹‰à¸²à¸ˆà¸°à¹ƒà¸«à¹‰ airflow à¹€à¸‚à¹‰à¸²à¸–à¸¶à¸‡
  user: "${AIRFLOW_UID:-50000}:0"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
    - "5432:5432"

  airflow-init:
    <<: *airflow-common
    build: .
    command: bash -c "airflow db init && airflow users create --username admin --password admin --firstname admin --lastname user --role Admin --email admin@example.com"
    depends_on:
      - postgres

  webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      - postgres

  # ðŸ‘‡ à¹€à¸žà¸´à¹ˆà¸¡ Flask web app
  web:
    build: .
    command: python main.py
    volumes:
      - ./:/opt/airflow        # ðŸ‘ˆ mount à¸—à¸±à¹‰à¸‡ project root
    working_dir: /opt/airflow
    ports:
      - "5000:5000"   # Flask app à¹€à¸›à¸´à¸”à¸—à¸µà¹ˆ localhost:5000
    depends_on:
      - postgres
    environment:
      FLASK_ENV: development

# âœ… à¸›à¸£à¸°à¸à¸²à¸¨ volume à¸•à¸£à¸‡à¸™à¸µà¹‰
volumes:
  postgres-db-volume:
